version: "3.8"
services:
  app:
    container_name: express
    build: .
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./
        target: /app
    environment:
      - DB_USER=${DB_USER}
      - DB_HOST=${D_DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:15.6
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  db:
