version: "3.8"
services:
  app:
    container_name: express
    build: .
    ports:
      - "3001:3001"
    volumes:
      - type: bind
        source: ./
        target: /app
    environment:
      - DB_USER=${DB_USER}
      - DB_HOST=${D_DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:15.6
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

nginx:
  container_name: nginx
  image: nginx:latest
  ports:
    - "80:80"
  volumes:
    - type: bind
      source: ./nginx.conf
      target: /etc/nginx/nginx.conf
  depends_on:
    - app

volumes:
  db:
